config/routes.rb
Rails.application.routes.draw do

  # get 'list/new'
  root :to => 'pages#home'
  get "/" => 'pages#home'

  resources :styles
    get '/new' => 'styles#new'
    get '/by_type' => 'styles#by_type', as: :by_type
    get '/show/:name' =>'style#show', as: :style_show




  resources :attires
    get '/new' => 'attires#new'
    get '/by_type/:attire' => 'attires#by_type', as: :by_type
    get '/show/:name' => 'attire#show', as: :attire_show


  resources :users
    get '/new' => 'users#new'
    get '/login' => 'session#new'
    post '/login' => 'session#create'
    delete '/login' => 'session#destroy', as: :destroy

    get '/fav_attires' => 'users#fav_attires'

    post '/fav_attires/add' => 'users#add_to_fav_attires'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attire.rb
# == Schema Information
#
# Table name: attires
#
#  id         :bigint(8)        not null, primary key
#  name       :text
#  catagory   :text
#  fashion    :text
#  detail     :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Attire < ApplicationRecord
  belongs_to :style, :optional => true
  has_and_belongs_to_many :users
  enum attire_type: [:accessories, :bottom, :dress, :hat, :shoe, :top]
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :attires
  enum style_type: [:casual, :sexy, :sophisticated, :vintage]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint(8)        not null, primary key
#  name       :text
#  email      :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_and_belongs_to_many :attires
  has_many :styles, through: :attires
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/attires_controller.rb
class AttiresController < ApplicationController
  def new
    @attire = Attire.attire_types.keys
  end

  def by_type
    @attire = Attire.where(:attire_type => params[:attire])
  end

  def show
    @attire = Attire.find params[:id]
  end


end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end


  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid login or password"
      redirect_to user_login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path

  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController


  def new
    @style = Style.style_types.keys
  end

  def by_type
    @style = Style.where(:style_type => params[:style])

  end

  def show
    @style = Style.find params[:id]
    @style_clothes = Style.where(:style_type => @style.style_type)

    @style_random = @style_clothes.sample 3
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_for_admin, :only => true

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    cloudinary = Cloudinary::Uploader.upload( params[ "user" ][ "image" ] )
    @user.image = cloudinary["url"]
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
    else
      render :new
  end

  def fav_attires
    @user = User.find params[:user_id]
    @fav_attires = @user.attires
  end

  def add_to_fav_attires
    attire = Attire.find params[:attire_id]
    @current_user.attires << attire
    redirect_to users_fav_attires_path(@current_user)

  end

end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attires_helper.rb
module AttiresHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attires/by_type.html.erb
<div class="container">
  <div class="title">
    <h1><%= params[:attire].capitalize %></h1>
  </div>

  <div class=“container”>
      <div class ="grid_container">
      <% @attire.each do |attire| %>

      <p class ="box">  
          <%= link_to image_tag(attire.image, :class => 'thumb'), attire_path(attire)  %>
          <%= attire.name%>
      </p>
          <% end %>

      </div>
  </div>
</div>

app/views/attires/new.html.erb
<div class="title">
  <h1>Attire Type</h1>
</div>

  <div class = "container">
    <div class = "attire_new">
      <div class ="row">
        <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("dress.png", :alt => "dress", :title => "Dress", :class => 'thumb_attire'), attire_by_type_path(@attire[2])) %>
        </div>
        <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("top.png", :alt => "top", :title => "Top", :class => 'thumb_attire'), attire_by_type_path(@attire[5])) %>
        </div>
          <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("bottom.png", :alt => "Bottom", :title => "Bottom", :class => 'thumb_attire'), attire_by_type_path(@attire[1])) %>
        </div>
          <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("shoes.png", :alt => "Shoes", :title => "Shoes", :class => 'thumb_attire'), attire_by_type_path(@attire[4])) %>
        </div>
          <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("hat.png", :alt => "Hats", :title => "Hats", :class => 'thumb_attire'), attire_by_type_path(@attire[3])) %>
        </div>
          <div class="mx-auto col-md-2 col-sm-2 col-xs-2">
          <%= link_to(image_tag("accessories.png", :alt => "Accessories", :title => "Accessories", :class => 'thumb_attire'), attire_by_type_path(@attire[0])) %>
        </div>
      </div>
    </div>
  </div>

  <div class = "container">
    <div class = "attire_new_text">
      <div class ="row">
        <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Dresses</h3>
        </div>
          <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Top</h3>
        </div>
          <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Bottom</h3>
        </div>
          <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Shoes</h3>
        </div>
          <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Hats</h3>
        </div>
          <div class="mx-auto col-md-2 col-sm-3 col-xs-3">
          <h3>Accessories</h3>
        </div>
      </div>
    </div>
  </div>

app/views/attires/show.html.erb
<div class="container">
  <div class="wrapper">
      <div class ="show_img">
        <%= image_tag @attire.image, :alt => @attire.name, :class => 'feature2'%>

      </div>

      <div class ="associate_img">
          <p class = "thumb_text">
            <h4>Associate Style </h4>
            <% if @attire.style.present? %>
            <%= link_to image_tag(@attire.style.image, :class =>'thumb2'), style_path(@attire.style.id)  %>
            <br>
            <%= @attire.style.style_type.capitalize %>
            <% end %>
          </p>
    </div>

    <div class = "nested">
      <% if @attire.style.present? %>
        <div>
          <h1 class ="item_name"><%= @attire.name.capitalize  %></h1>
        </div>
        <div>
            <ul>
              <li>Style: <%= @attire.style.style_type %></li>
              <p></p>
              <li>Description : <%= @attire.detail %></li>
            </ul>
        </div>
      <% else %>
      <div>
        <h1> Not available</h1>
      </div>
      <div>
        <h4> Not available</h4>
      </div>
      <% end %>

      <div class ="all_size">
        <a href="", class="size"> S </a>
        <a href="", class="size"> M </a>
        <a href="", class="size"> L </a>
      </div>

      <div class="fav_controller">
        <% if @current_user.present? %>
          <div class="add_button">

              <%= button_to "Add Fav List", "/users/fav_attire", :method => 'post', :class => "btn btn-dark", form: {style: 'display:inline-block;'}%>
          </div>

          <div class="add_button">
            <button type="button" class="btn btn-dark">
              <a href="", class = "add_list">Add Cart</a>
            </button>
          </div>

          <% else %>
          <div class="join_us_button">
            <%= button_to 'Ready to Shop?', '/users/new', :method => 'get', :class => "btn btn-dark", form: {style: 'display:inline-block;'} %>

          </div>

          <% end %>
        </div>

    </div>

  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Paytone+One|Varela+Round|Abril+Fatface|Chela+One|Lobster|Roboto|Montserrat|Raleway|Pacifico|Montserrat:300,400');
      </style>
  </head>

  <body>

    <nav class ="navbar navbar-dark bg-dark navbar-expand " >
   <div class ="container">
      <div class="text-center d-flex flex-row justify-content-around my-flex-container col-md-4 col-sm-4">
       <%= link_to 'Home', root_path, :class => "nav_round"  %>
         <% if @current_user.present? %>
           <%= link_to 'User list', users_path if @current_user.admin? %>
          <p class = "nav_round_user" >
           <%= @current_user.name%>
          </p>
           <%= link_to "Sign out", destroy_path(@current_user.id), :method => 'delete', :class => "nav_round"  %>

         <% else %>
           <%= link_to 'Create', new_user_path, :class => "nav_round"  %>
           <%= link_to 'Log In', login_path, :class => "nav_round"  %>
         <% end %>
      </div>

      <div class="text-center d-flex flex-row justify-content-around my-flex-container col-md-4 col-sm-4">
         <%= image_tag 'Logo_long_white.png', :alt => "Chole logo", :class => 'home_logo' %>
      </div>

      <div class="text-center d-flex flex-row justify-content-around my-flex-container col-md-4 col-sm-4">
         <%= link_to 'Style', new_style_path, :class => "nav_round"  %>
         <%= link_to 'Attire', new_attire_path, :class => "nav_round"  %>
         <%= link_to 'My List', fav_attires_path(@current_user), :class => "nav_round" %>
      </div>
     </div>
   </nav>

<div class ="container_footer">
   <%= yield %>
<div class ="container">



   <footer class="fixed-bottom">
      <p>Sherine.GA.WDI28 &copy; 2018  <p>
   </footer>

  </body>
</html>

app/views/list/new.html.erb
<h1>List#new</h1>
<p>Find me in app/views/list/new.html.erb</p>

app/views/pages/home.html.erb
<div class ="container ">

    <div class="row">
      <div class="home_img_content">
        <div class="mx-auto col-md-4 col-sm-4 col-xs-4">
          <%= link_to(image_tag("style_home3.jpg", :alt => "Fashion Style", :title => "Fashion Style", :class => 'home_img', :id => 'home_img1'), new_style_path )%>
          <div class="overlay">
            <span id="text"> <%= link_to "Fashion Style", new_style_path %> </span>
          </div>
        </div>

        <div class="mx-auto col-md-4 col-sm-4 col-xs-4">
          <div class="user_content">
          <% if @current_user.present? %>
            <h2>Welcome back</h2>
            <div>
              <%= image_tag @current_user.image, :alt => @current_user.name, :class => "user" if @current_user.image.present?%>

            </div>
              <h2><%= @current_user.name %></h2>
            <% else %>
                <%= image_tag("Logo_square_black.png", class: "home_content_logo")%>

            <% end %>
          </div>
        </div>
        <div class="mx-auto col-md-4 col-sm-4 col-xs-4">
          <%= link_to(image_tag("Aatire_range.png", :alt => "Clothing", :title => "Clothing", :class => 'home_img'), new_attire_path )%>
          <div class="overlay1">
            <span id="text"> <%= link_to "Attire Range", new_attire_path  %> </span>
          </div>
        </div>

    </div>
  </div>

app/views/session/new.html.erb
<div class="container">

  <div class="title_home">
      <h1>Log In</h1>
      <h2 class="errors"><%= flash[:error] %></h2>
  </div>

    <div class ="wrapper3">
      <div class="form">
      <%= form_tag login_path do %>
        <%= label_tag :email %>
        <%= email_field_tag :email %>
        <p></p>
      <br>

        <%= label_tag :password %>
        <%= password_field_tag :password %>

      <br>
      <p></p>
        <%= submit_tag "Log In", class: "btn btn-dark" %>
      </div>

    <div class = "form">
      <h2>New Member?</h2>
      <p class="new_member">Create your account with just 3 simple inputs </p>
      <% end %>

        <%= button_to 'Create New Account', new_user_path, :method => 'get', :class => "btn btn-dark", form: {style: 'display:inline-block;'} %>
    </div>

  </div>
</div>

app/views/styles/by_type.html.erb
<div class="container">

  <div class="title">
    <h1> <%= params[:style].capitalize %> Fashion Style </h1>
  </div>

  <div class=“container”>
      <div class ="grid_container">
        <% @style.each do |style| %>

        <p class ="box">
          <%= link_to image_tag(style.image, :class => 'thumb'), style_path(style) %>
          <%= style.name %>
        </p>

        <% end %>

        </div>
  </div>
</div>

app/views/styles/new.html.erb
<div class = "container">
<div class="title">
  <h1>Fahsion Style</h1>
</div>

  <div class = "container">
    <div class = "fashion_type">
      <div class ="row">
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <%= link_to(image_tag("casual.png", :alt => "casual", :title => "Casual", :class => 'feature'), style_path(@style[0])) %>
        </div>
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <%= link_to(image_tag("sophisticated.png", :alt => "sophisticated", :title => "Sophisticated", :class => 'feature')) %>
        </div>
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <%= link_to(image_tag("vintage.png", :alt => "vintage", :title => "Vintage", :class => 'feature')) %>
        </div>
         <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <%= link_to(image_tag("sexy.png", :alt => "sexy", :title => "Sexy", :class => 'feature')) %>
        </div>
      </div>
      <div class ="row">
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <h3>Casual Style </h3>
        </div>
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <h3>Sophisticated Style </h3>
        </div>
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <h3>Vintage Style </h3>
        </div>
        <div class="mx-auto col-md-3 col-sm-3 col-xs-3">
        <h3>Sexy Style </h3>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/styles/show.html.erb
<div class="title">
  <h1><%= @style.name.capitalize  %></h1>
</div>
<div class="container">
  <div class="wrapper2">
        <div>
            <%= image_tag @style.image, :alt => @style.name, :class => 'feature' if @style.image.present?%>
            <h5>Associate Style: <%= @style.style_type.capitalize %> </h5>
        </div>

        <div class ="associate_img_style">
            <h3>Associate Attire</h3>
            <% @style.attires.each do |attire| %>
              <%= link_to image_tag(attire.image, :class =>'thumb4'), attire %>
              <br>
              <%= attire.attire_type %>
              <br>
              <p></p>
            <% end %>

        </div>

        <div class ="associate_img_style">
            <h3>You may like</h3>
            <% @style_random.each do |random| %>
              <% next if random == @style %>
                <%= link_to image_tag(random.image, :class => 'thumb3'), random %>
                <br>
                <%= random.name %>
                <br>
                <p></p>
            <% end %>

        </div>
  </div>
</div>

app/views/users/fav.html.erb
<h1><%= @current_user.name %></h1>

app/views/users/fav_attires.html.erb
<div class ="container">
  <div class="title">
    <h1>My Favorite Attire List</h1>
  </div>

  <div class=“container”>
      <div class ="grid_container">
        <% @fav_attire.each do |f_attire| %>

        <p class ="box">
          <%= link_to image_tag(f_attire.image, :class => 'thumb'), attire_path(style) %>
          <%= f_attire.name %>
        </p>

        <% end %>

        </div>
  </div>




</div>

app/views/users/index.html.erb
<div class="title">
  <h1>ALL Users: <%= number_to_human User.count %></h1>
</div>
  
<% @user.each do |user| %>
  <p><%= user.name %>
  </br>
  <%= user.email %>
  <br>
  <%= user.image %>
</p>
<% end %>

app/views/users/new.html.erb
<div class="container">

  <div class="title_home">
    <h1>Create New Account</h1>
  </div>

  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>
  <div class ="container">
    <div class ="wrapper3">
      <div class="form">
        <%= form_for(@user, :html => { :multipart => true }) do |f| %>

            <%= f.label :name, :class =>"test" %>
            <%= f.text_field :name %>
            <p></p>
          <br>

            <%= f.label :email %>
            <%= f.email_field :email %>
            <p></p>
          <br>

            <%= f.label :image %>
            <%= f.file_field :image,  :class => "btn btn-dark"%>

        </div>

        <div class="form">
            <%= f.label :password %>
            <%= f.password_field :password %>
            <p></p>
          <br>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
            <p></p>
          <br>

            <%= f.submit "Create!", :class => "btn btn-dark"%>
        </div>
          <% end %>

    </div>
  </div>

</div>